# Generated by Django 3.0 on 2022-02-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.Users')),
                ('relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.Users')),
            ],
            options={
                'db_table': 'Relations',
                'unique_together': {('relation_id', 'follower_id')},
            },
        ),
    ]
