# Generated by Django 3.0 on 2022-02-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='following_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relations',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='relations',
            unique_together={('follower_id', 'following_id')},
        ),
        migrations.RemoveField(
            model_name='relations',
            name='relation_id',
        ),
    ]
